import { SpeechUtility } from './src/main/ets/SpeechUtility';
import { AudioRecorder } from './src/main/ets/media/AudioRecorder';
import { SpeechRecognizer } from './src/main/ets/SpeechRecognizer';
import { RecognizerListener } from './src/main/ets/impl/RecognizerListener';
import { AsrDetail } from './src/main/ets/model/AsrResultData';
import { SpeechException } from './src/main/ets/utils/exception/SpeechException';

export { SpeechUtility, AudioRecorder, SpeechRecognizer, RecognizerListener, AsrDetail, SpeechException }